### ISSUE TITLE
Disable command logs (with flag)

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#162]
When a CLI command is called from the pipeline, the `docker-entrypoint.sh` script verifies the user, connects credentials and prints logs (`Successfully logged in` etc.). After that, the preview command that requires a JSON output is called and those logs get into the stdout. As a workaround we take the tail of the output like this:
```
OUTPUT=$(/root/docker-entrypoint.sh preview update $UFFIZZI_ENVIRONMENT_ID $UFFIZZI_COMPOSE_FILE --output=json --set-labels project=$CI_PROJECT_NAME-$CI_PROJECT_ID-$CI_MERGE_REQUEST_IID | tail -n 1)
```
Some possible solutions:
- Add a --verbose flag with different values (0 - disable all stdout, 1 - disable only command logs, 2 - enable all stdout)
- Add some key to the JSON output (for example `json: `) so it can be easily found using grep

**Comment by moklidia** [comment]
@axisofentropy We do disable stdout if the `--output-format=json`, but in this case, logs come from commands executed before the command we pass that flag into (like `uffizzi login` or `uffizzi connect`).

**Comment by gadkins** [comment]
This issue is not clear to me. What problem is this solving? 

@axisofentropy @moklidia

**Comment by moklidia** [comment]
Not relevant anymore
