### ISSUE TITLE
Logs(1/n) Basic formatting

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#177]
Handle the new logs structure:
```
{ logs: { timestamp:, payload: } }
```

**Comment by moklidia** [comment]
@fedorov-dualboot Need to check that timestamps are added to logs

**Comment by fedorov-dualboot** [comment]
tested. **OK**. logs structure udated. ![image](https://user-images.githubusercontent.com/110913994/202691487-fcda3422-8e78-4ccb-9ad7-1934d0f8d94f.png)
