### ISSUE TITLE
Fatal Error "System Fault" After Deployment Update

### ISSUE THREAD

**Issue by axisofentropy** [UffizziCloud/uffizzi_cli#218]
A few open-source GHA runs failed this week due to the CLI saying `System Fault` and exiting. These happened _after_ a Deployment was  updated (probably successfully?), so the core feature "worked" but then the PR comments did not get updated because the workflow ended. I don't see any fatal errors in our web container logs at this time.

Here's one example workflow run: https://github.com/backstage/backstage/actions/runs/4839801455/jobs/8625054835#step:15:28
Timestamp: `Sat, 29 Apr 2023 16:49:16 GMT`
Container specification log entry: https://console.cloud.google.com/logs/query;cursorTimestamp=2023-04-29T16:49:18.663355894Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22uffizzi-pro-production-gke%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22uffizzi-platform%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fapp%3D%22web%22%0Atimestamp%3D%222023-04-29T16:49:18.243454595Z%22%0AinsertId%3D%22yykm9f8bev8dxjdx%22;timeRange=2023-04-29T16:50:35.135Z%2F2023-04-29T16:50:35.135Z--PT1H?project=uffizzi-pro-production-gke

**Comment by moklidia** [comment]
Haven't been reproduced ever since, closing
