### ISSUE TITLE
Alias `preview` as `compose`

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#225]
As we add support for `cluster` to the `uffizzi` CLI, we should alias `preview` as `compose` to distinguish it as a Docker Compose deployment. However, the existing `preview` commands should still work to ensure backward compatibility. Going forward we will start to refer to `uffizzi compose create` and `uffizzi cluster create` as the two ways to create environments on Uffizzi

**Comment by moklidia** [comment]
Duplicate of https://github.com/UffizziCloud/uffizzi_cli/issues/265
