### ISSUE TITLE
`uffizzi cluster describe`

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#229]
```
$ uffizzi cluster describe happy-lion
  NAME: happy-lion
  LAST DEPLOYED: Tue Oct 22 09:27:17 2023
  NAMESPACE: happy-lion
  STATUS: deployed
  REVISION: 1
```

**Comment by gadkins** [comment]
There may be other information we should include in the cluster description. @zipofar @axisofentropy @waveywaves please make recommendations

**Comment by zipofar** [comment]
At this moment we only have next items for clusters:
```
Name:
State:
```

**Comment by gadkins** [comment]
Let's display the following fields when executing the `describe`:
```
$ uffizzi cluster describe happy-lion
  NAME: happy-lion
  CREATED: Tue Oct 22 09:27:17 2023
  STATUS: deployed
```

**Comment by ALEXANCHESSS** [comment]
<img width="582" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/31a08d72-0a1d-474d-91e8-9b61dcd6122b">

- format "CREATED" DateTime different from the requirements
- swap lines "CREATED" and "STATUS"

**Comment by zipofar** [comment]
Format of `CREATED` is fixed

**Comment by ALEXANCHESSS** [comment]
An error accurse when the calling command
<img width="592" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/64f3ca0f-01a2-4727-a201-02fce2c53715">

**Comment by ALEXANCHESSS** [comment]
**TESTED OK**
<img width="502" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/f6cb7092-c801-44a7-b7b4-3c69f5d6f839">
