### ISSUE TITLE
Handle error when kubeconfig file is another file (e.g. manifest)

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_cli#243]
Case when we update kubeconfig file that is not a kubeconfig
```
#> uffizzi cluster update-kubeconfig --kubeconfig="~/.config/uffizzi/manifest.yml" --name="zip-1"
CLI Error:
undefined method `detect' for nil:NilClass
```

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
<img width="850" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/05e399ee-4450-40c1-bc5b-df885b0fb2cb">
