### ISSUE TITLE
`uffizzi cluster disconnect` command to switch back to original kubeconfig

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_cli#258]
currently we can only connect to a cluster using the update-kubeconfig command, it would be nice to switch back from that to the original cluster otherwise the user will have to manually switch the kubecontext to the original cluster which is not a good ux.

**Comment by zipofar** [comment]
## HOT TO TEST: ##
# 1. Case
* We have some context in kubeconfig
* Create new cluster and update kubeconfig
* Do `disconnect`
* Current context should return to original context

# 2. Case
* We have kubeconfig for default path (e.g. ~/.kube/config)
* We have kubeconfig by not default path (e.g. ~/my-kubeconfig)
* We create cluster and and update kubeconfig to `~/my-kubeconfig`
* Do `disconnect kubeconfig="~/my-kubeconfig"`
* Current context should return to original context for path `~/my-kubeconfig`
* Current context for `~/.kube/config` should't change
