### ISSUE TITLE
Only developers that create a cluster should manage it

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#262]
Currently, all developers on an account can see a list of all clusters on an account and delete clusters deleted by other developers on the account. They can also run `update-kubeconfig` to access clusters created by other developers.  

We should change this behavior such that only the developer that creates a cluster may delete it or get access via update-kubeconfig. Similarly, when the developer runs `uffizzi cluster list` they should only see clusters that they have created.  

Admins should still be able to  list, delete, and update-kubeconfig for all clusters.

**Comment by ALEXANCHESSS** [comment]
The developer can see the name of the cluster created by another user.

**Steps:**
1. Create a second GitHub account
2. Add an organization to the team as an admin of the GitHub organization
3. Add a developer to the team
4. On the platform, create a project in the organization
5. Log in to the CLI as an administrator
6. Select the organization project and create a cluster in it
7. Log in to the CLI as a developer
8. View the list of clusters

**Expected result:** The list of clusters is empty
**Actual result:** The cluster created by the admin is displayed.

<img width="666" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/897c6a02-dbb2-42f9-b273-a413d2228f07">

**Comment by moklidia** [comment]
@ALEXANCHESSS Please test with this [preview](https://app.uffizzi.com//github.com/UffizziCloud/uffizzi_platform/pull/1121)

These three issues are related:
https://github.com/UffizziCloud/uffizzi_cli/issues/262
https://github.com/UffizziCloud/uffizzi/issues/451
https://github.com/UffizziCloud/uffizzi_platform/issues/1120

**Comment by ALEXANCHESSS** [comment]
1. Change the "Unauthorized" error on "Cluster Not Found" if the developer interacts with a cluster to which he doesn't have access
<img width="373" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/78291807-9146-4b71-8b96-44fdf5bf8b1d">

2. Admin doesn't see the cluster which has been created by another user in the list of clusters but can interact with it
<img width="498" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/e1bab52c-19b8-4c21-b601-f13e38663032">

**Comment by moklidia** [comment]
@ALEXANCHESSS This is fixed
https://github.com/UffizziCloud/uffizzi_cli/issues/262#issuecomment-1649618392

Please also check this case with GHA: https://github.com/UffizziCloud/uffizzi_cli/issues/262#issuecomment-1649732613

**Comment by ALEXANCHESSS** [comment]
1) The developer does not have access to the cluster lists through the GHA
<img width="1710" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/0c071b3f-4526-4bf2-8cd9-9d0b15278d3c">

**Comment by moklidia** [comment]
Please test with `UffizziCloud/cluster-action@image_version` and with `image: uffizzi/cli:pr-285` as an argument

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
