### ISSUE TITLE
Rename `uffizzi preview` to `uffizzi compose`

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#265]
Rename the preview command to `compose` to distinguish it from `cluster` environments.  

#### Other updates
- Update the DESCRIPTION on the `help` page for `uffizzi preview create` to "Run $ uffizzi project compose --help for details."  
- Fix typo "usefull"  in FLAGS description - Should be "useful" 
> --set-labels=METADATA
           Metadata of deployment that contains any information which can
           be usefull for filtering deployments.

- Fix FLAGS wording for `uffizzi preview list help`. Should be "Metadata to filter list of deployments."

**Comment by gadkins** [comment]
@zipofar Update the help description to:

> Manage Uffizzi compose environments (previews) and view logs

**Comment by moklidia** [comment]
Done in https://github.com/UffizziCloud/uffizzi_controller/issues/92

**Comment by ALEXANCHESSS** [comment]
- [ ] command `uffizzi compose list help` doesn't work
- [ ] Fix typo "usefull" in FLAGS description - Should be "useful"
- [ ] Fix FLAGS wording for uffizzi preview list help. Should be "Metadata to **_filter_** list of deployments."

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
