### ISSUE TITLE
Add flag `--update-current-context` to cluster create

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_cli#277]
[Sluck thread](https://dualbootpartners.slack.com/archives/CN8MKSAQ5/p1689864846363119?thread_ts=1689843331.580939&cid=CN8MKSAQ5)

As Vibhav suggests, let’s use the option `--update-current-context `:
```
uffizzi cluster create [CLUSTER_NAME] --update-current-context
```

If the user runs uffizzi cluster create without this option, add the command to update kubeconfig in the message dispalyed:

```
uffizzi cluster create -n foo
[✔] Creating cluster foo...
Cluster with name: foo was created.

To update the current context, run:
$ uffizzi cluster update-kubeconfig --name foo
```

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
