### ISSUE TITLE
Bug: project creation

### ISSUE THREAD

**Issue by zipofar** [UffizziCloud/uffizzi_cli#280]
```
Login to Uffizzi server.
https://app.uffizzi.com/sign_in?session_id=d77f8130-baf9-4155-b34a-fa905a7093d8
Login successfull
Select an account: zipofar
Select a project or create a new project: Create a new project
Project name:  cluster-test
Project slug:  cluster-test-h28xoe
Project desciption:
CLI Error:
undefined method `first' for "This project name already exists. Uffizzi project names must be unique.":String
```

**Comment by ALEXANCHESSS** [comment]
1. Change the error "Project with name 'project_name' already exists" to "A project with the name 'project_name' already exists"
2. After unsuccessful entry of the project name, implement the possibility of re-entering the project name

**Comment by ALEXANCHESSS** [comment]
@zipofar 
If you enter any value other than "y" or "n" in the question box, it will be treated as "n". You need to add a variant event where the user made a mistake and entered an incorrect value. After the incorrect value is entered, re-display the selection question
`A project slug 'projex-y-3b22l1' already taken.`
`Do you want to try different project params? (y/n)  b`
`Project creation aborted. You can run 'uffizzi config' to set project as a default`

**Comment by ALEXANCHESSS** [comment]
**TESTED - OK**
<img width="672" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/6e5843d4-2c40-4a31-914c-574c89aeb566">
