### ISSUE TITLE
Handle command name errors

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_cli#317]
- Run binary
- Make mistake in the command name 'uffizzi cluster lits'

Actual result: the ruby backtrace is shown to the user.
Expected result: a message that such command does not exist

**Comment by zipofar** [comment]
Can't reproduce this on MacOS 10, Linux 22,

```
# uffizzi unknown-command
Could not find command "unknown-command".
```

```
# uffizzi cluster lits
Could not find command "lits".
Did you mean?  "list"
```
