### ISSUE TITLE
Various CLI updates

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#324]
- [x] Make `--update-current-context` default to true (i.e. user should set `--update-current-context=false`)  
- [x] Do not require `--name` / `-n` option (use positional argument)  
- [x] Make `--delete-config` default to true (i.e. user should set `--delete-config=false`)  
- [x] Handle ctl+c (currently get a stack trace)  
- [ ] ~~Default to account that corresponds to last created cluster when user runs `uffizzi login`~~
- [ ] Do not list projects that user does not have access to in UI 
- [x] CLI typo “Login successfull” — should be "successful"  
- [x] Do not prompt to enter Username when user logs in via email `uffizzi login --email jdoe@example.com`

**Comment by axisofentropy** [comment]
Could we also not ask for the server and assume `https://app.uffizzi.com` unless otherwise specified?

**Comment by zipofar** [comment]
> Do not list projects that user does not have access to in UI
Can't reproduce

**Comment by ALEXANCHESSS** [comment]
- [ ] Make `--update-current-context` default to true (i.e. user should set `--update-current-context=false`)  
- [ ] Do not require `--name` / `-n` option (use positional argument)  
- [ ] Make `--delete-config` default to true (i.e. user should set `--delete-config=false`)  
- [ ] Handle ctl+c (currently get a stack trace)  
- [ ] CLI typo “Login successfull” — should be "successful"  
- [x] Do not prompt to enter Username when user logs in via email `uffizzi login --email jdoe@example.com`

**Comment by ALEXANCHESSS** [comment]
Update text `u cluster create -h`:
<img width="603" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/f38d0812-e50e-401a-a178-4f628c734717">

**Comment by ALEXANCHESSS** [comment]
@zipofar 
-  [ ] fix text `u cluster create -h`
<img width="603" alt="267925963-f38d0812-e50e-401a-a178-4f628c734717" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/363c00bd-1b54-48f5-ae32-17d2014df6b7">

- [ ] When deleting a cluster, an error occurs and the cluster is not removed from the kubeconfig
<img width="350" alt="image" src="https://github.com/UffizziCloud/uffizzi_cli/assets/91793094/d3e98729-b386-46ae-9706-507c5b394ac2">
