### ISSUE TITLE
uffizzi dev environments

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#333]

**Comment by zipofar** [comment]
### HOT TO TEST: ###
* gem build uffizzi.gemspec
* gem install uffizzi-cli-2.0.37.gem
* install skaffold ([doc](https://skaffold.dev/docs/install/))
* clone skaffold repo `git clone https://github.com/GoogleContainerTools/skaffold`
* go to skaffold/examples/ruby
* docker build -t ttl.sh/skaffold-ruby-example:1h backend/Dockerfile
* change `skaffold.yaml` artifacts.image to ttl.sh/skaffold-ruby-example:1h
* change `k8s/deployment.yaml` spec.template.spec.containers.image to ttl.sh/skaffold-ruby-example:1h
* uffizzi dev start
