### ISSUE TITLE
`uffizzi dev start` (code + build locally)

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#334]
## Summary
First iteration of [`uffizzi dev` environments](https://github.com/UffizziCloud/uffizzi/issues/481) should:  
- Support coding and building locally via skaffold.  
- In the background, this command should perform the equivalent of: `uffizzi cluster create --update-current-context`, then `skaffold dev --default-repo registry.uffizzi.com`  
- This command should wrap the `skaffold dev` functionality (See example app that uses skaffold [here](https://github.com/UffizziCloud/ucluster-skaffold-example/blob/main/skaffold.yaml)).  
- If the user interrupts the skaffold process with `ctrl` + `c`, then delete the uffizzi cluster  

## Scope of this issue

```
Usage: uffizzi dev start <config-file> [OPTIONS]

Start a new dev environment on Uffizzi clusters.

Options:
  --name           Name for the dev environment (Optional | Auto-assigned) 
  --kubeconfig     Path to kubeconfig
  --help           Show this message and exit.
  --default-repo   Overrides the global default image registry (registry.uffizzi.com)  
```

## Notes  
- Bundle skaffold with Uffizzi CLI, such that the user can run `skaffold` commands if needed.
- Default configuration will be to code and build locally (i.e. user should  not have to specify `--code` or `--build` options
- If the user does not have a scaffold.yaml file at the path to <config-file>, then prompt the user to check the file path or run `skaffold init`:  

```
$ uffizzi dev start
A valid dev environment configuration is required. Please provide a valid config, 
or run `skaffold init` to generate a skaffold.yaml configuration.  
See the `uffizzi dev start --help` page for supported configs and usage details.
```
- The default repo should be `registry.uffizzi.com`, but the user can override it with `--default-repo` option  
- Allow user to specify alternate path to kubeconfig with `--kubeconfig` option  
- Allow user to specify a dev env name with `--name` option (Or auto-generate it if no name option is provided)  
- Delete cluster if user stops the skaffold process

**Comment by zipofar** [comment]
As the user is only able to create one dev environment, remove the NAME argument from the stop and start command
