### ISSUE TITLE
Add `uffizzi open` command for dev cluster ingress

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#348]
## Summary
Add a convenience function that automatically opens any ingresses configured for the current context cluster.  

This command should:  
- Extract all ingress from the current context (This is the equivalent of `kubectl get ingress -o json | jq -r '.items[]
.spec.rules[].host'`)  
- Prepend `https://` to each ingress to create a URL  
- Open a browser tab for each URL. Be sure this works for Linux, Mac, and Windows systems.  

## Example Usage
```
uffizzi open
```

Or `uffizzi open [CLUSTER_NAME]`

**Comment by gadkins** [comment]
@moklidia @zipofar Let's use the command `uffizzi ingress open`

**Comment by moklidia** [comment]
@gadkins Is this going to work only with dev environments? How about `uffizzi dev ingress open` then?

**Comment by moklidia** [comment]
@zipofar Please change to `uffizzi dev ingress open`
