### ISSUE TITLE
Clean up CLI status and output messages

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_cli#410]
Fix the following typos and misleading output messages:  

1. When running `uffizzi install`, the word "address" is misspelled (it says "addess"). Also add the word "on", as in: “Waiting on IP address...
2.Remove the status message “Waiting on certificate creation for the controller host…” (the check is done AFTER the install command finishes and the user has updated their dns.)  
3. The `-n` option should also work when running `uffizzi uninstall` (only `--namespace` works right now)  
3. When error message that results from `uffizzi uninstall -n uffizzi`, has a misspelling (“HOSTNMAE” should be "HOSTNAME).

**Comment by waveywaves** [comment]
Couldn't find HOSTNMAE anywhere in the codebase, might already be fixed
