### ISSUE TITLE
BUG: Error after adding docker account with invalid credentials

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_cli#81]
Try to add docker account with invalid credentials

- Run uffizzi connect docker-hub
- Type invalid login and password

![image](https://user-images.githubusercontent.com/10543986/164236298-93f7df45-df2d-49f3-a32f-2fd098f35621.png)

**Comment by the38th** [comment]
couldn't reproduce on develop branch. I think this issue isn't actual anymore

**Comment by NealArw** [comment]
Not actual.
